-- Q1. What is the total revenue generated by male vs female cutomers?


SELECT gender, 
	   SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY gender


-- Customers who used a discount and spent more than the overall average purchase amount

SELECT customer_id, 
	   purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 item_purchased, 
	   ROUND(AVG(review_rating), 2) AS 'Average Product Rating'
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC


-- Q4. Compare the average purchase amounts between Standard and Express Shipping

SELECT shipping_type,
	   AVG(purchase_amount) AS 'Average Product Amount'
FROM customer
WHERE shipping_type = 'Standard' OR shipping_type = 'Express'
GROUP BY shipping_type


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between
-- subscribers and non-subscribers


SELECT subscription_status,
	   COUNT(customer_id) AS 'Total Customers',
	   AVG(purchase_amount) AS 'Average Spend',
	   SUM(purchase_amount) AS 'Total Spend'
FROM customer
GROUP BY subscription_status
ORDER BY SUM(purchase_amount) DESC


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5 item_purchased,
	   CAST(
	   100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)
	   AS DECIMAL(5,2)) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC


-- Q7. Segment customers into new, returning, and loyal based on their total number 
-- of previous purchases, and show the count of each segment

WITH customer_type AS(
SELECT customer_id,
	   previous_purchases,
	   CASE WHEN previous_purchases = 1 THEN 'New'
	   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	   ELSE 'Loyal'
	   END AS customer_segment
FROM customer
)
SELECT customer_segment,
	   COUNT(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment


-- Q8. What are the top 3 most purchased products within each category?

WITH item_count AS(
SELECT category, 
	   item_purchased,
	   COUNT(customer_id) AS total_orders,
	   ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, 
	   category,
	   item_purchased,
	   total_orders
FROM item_count
WHERE item_rank <= 3


-- Q9. Are customers who are repeat buyer (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status


-- Q10. What is the contribution of each age group to the revenue?

SELECT age_group,
	   SUM(purchase_amount) AS total_revenue,
	    CAST(100.0 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER ()
        AS DECIMAL(6,2)) AS pct_of_total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC